spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: news-system-prod
      auto-index-creation: true

logging:
  file:
    name: ./logs/log4j2.txt
  level:
    by:
      stas:
        nms: info

hazelcast:
  cluster:
    name: news-management-cluster
  map:
    ttl: 10