spring:
  datasource:
    url: jdbc:mysql://localhost:3306/news_manager?createDatabaseIfNotExist=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 1234
  jpa:
    hibernate:
      ddl-auto: update