server:
  port: 8080

spring:
  application:
    name: nms-application
  config:
    import: configserver:http://nms-config-server:8888
  profiles:
    active: dev

management:
  endpoints:
    web:
      exposure:
        include: "*"